# Generated by Django 4.2.30 on 2026-06-13 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greenhouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('fan', 'Fan'), ('pump', 'Pump'), ('light', 'Light')], max_length=20)),
                ('condition_type', models.CharField(choices=[('time', 'Time-based'), ('sensor', 'Sensor-based')], max_length=10)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('sensor_name', models.CharField(blank=True, choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('soil_moisture', 'Soil Moisture'), ('light_intensity', 'Light Intensity')], max_length=20, null=True)),
                ('operator', models.CharField(blank=True, choices=[('>', 'Greater than'), ('<', 'Less than'), ('>=', 'Greater or equal'), ('<=', 'Less or equal'), ('==', 'Equal')], max_length=5, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('action', models.CharField(choices=[('on', 'Turn On'), ('off', 'Turn Off')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='greenhouses.greenhouse')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedules_schedule',
                'ordering': ['condition_type', 'time_of_day'],
            },
        ),
    ]
