# Generated by Django 4.2.30 on 2026-06-13 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('offline', 'Offline'), ('deleted', 'Deleted')], default='pending', max_length=10)),
                ('api_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greenhouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Greenhouse',
                'verbose_name_plural': 'Greenhouses',
                'db_table': 'greenhouses_greenhouse',
            },
        ),
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('greenhouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='device_state', serialize=False, to='greenhouses.greenhouse')),
                ('fan', models.BooleanField(default=False)),
                ('water_pump', models.BooleanField(default=False)),
                ('light', models.BooleanField(default=False)),
                ('energy_state', models.CharField(blank=True, choices=[('battery', 'Battery'), ('grid', 'Grid')], max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device State',
                'verbose_name_plural': 'Device States',
                'db_table': 'greenhouses_devicestate',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('soil_moisture', models.FloatField(blank=True, null=True)),
                ('light_intensity', models.FloatField(blank=True, null=True)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='greenhouses.greenhouse')),
            ],
            options={
                'verbose_name': 'Sensor Data',
                'verbose_name_plural': 'Sensor Data',
                'db_table': 'greenhouses_sensordata',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['greenhouse', '-timestamp'], name='idx_sensordata_gh_ts'), models.Index(fields=['timestamp'], name='idx_sensordata_timestamp')],
            },
        ),
        migrations.AddIndex(
            model_name='greenhouse',
            index=models.Index(fields=['owner', 'status'], name='idx_greenhouses_owner_status'),
        ),
    ]
